-- 0003_create_projects.sql
--
-- Introduces the Project aggregate persistence model.
-- SQLite remains the operational source of truth.
--
-- Conventions:
-- - identifiers are canonical UUID strings generated by the application;
-- - timestamps are UTC RFC 3339 strings;
-- - calendar dates use YYYY-MM-DD;
-- - archive and soft deletion are distinct lifecycle concepts.

CREATE TABLE projects (
    id TEXT PRIMARY KEY NOT NULL
        CHECK (
            length(id) = 36
            AND substr(id, 9, 1) = '-'
            AND substr(id, 14, 1) = '-'
            AND substr(id, 19, 1) = '-'
            AND substr(id, 24, 1) = '-'
        ),

    name TEXT NOT NULL
        CHECK (length(trim(name)) > 0),

    description TEXT,

    project_type TEXT NOT NULL
        CHECK (
            project_type IN (
                'custom',
                'learning',
                'certification',
                'reading',
                'software',
                'fitness',
                'administrative'
            )
        ),

    status TEXT NOT NULL DEFAULT 'active'
        CHECK (
            status IN (
                'active',
                'paused',
                'completed',
                'archived',
                'cancelled'
            )
        ),

    start_date TEXT
        CHECK (
            start_date IS NULL
            OR (
                length(start_date) = 10
                AND substr(start_date, 5, 1) = '-'
                AND substr(start_date, 8, 1) = '-'
            )
        ),

    target_date TEXT
        CHECK (
            target_date IS NULL
            OR (
                length(target_date) = 10
                AND substr(target_date, 5, 1) = '-'
                AND substr(target_date, 8, 1) = '-'
            )
        ),

    priority INTEGER NOT NULL DEFAULT 3
        CHECK (priority BETWEEN 1 AND 5),

    color TEXT,
    icon TEXT,
    objective TEXT,

    settings_json TEXT NOT NULL DEFAULT '{}'
        CHECK (json_valid(settings_json)),

    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    archived_at TEXT,
    deleted_at TEXT,

    CHECK (
        start_date IS NULL
        OR target_date IS NULL
        OR target_date >= start_date
    ),

    CHECK (
        (status = 'archived' AND archived_at IS NOT NULL)
        OR (status <> 'archived' AND archived_at IS NULL)
    ),

    CHECK (updated_at >= created_at),
    CHECK (archived_at IS NULL OR archived_at >= created_at),
    CHECK (deleted_at IS NULL OR deleted_at >= created_at)
);

CREATE INDEX idx_projects__status
    ON projects (status);

CREATE INDEX idx_projects__updated_at
    ON projects (updated_at DESC);

CREATE INDEX idx_projects__target_date
    ON projects (target_date)
    WHERE target_date IS NOT NULL;

CREATE INDEX idx_projects__active_listing
    ON projects (updated_at DESC, name ASC)
    WHERE deleted_at IS NULL
      AND status <> 'archived';

CREATE INDEX idx_projects__archived_listing
    ON projects (archived_at DESC, name ASC)
    WHERE deleted_at IS NULL
      AND status = 'archived';
